system_type: protein_ligand

inputs:
  complex: complex.pdb
  ligand: ligand.sdf

output_dir: outputs

prep:
  amber_level: low

fragit:
  central_fragment_resname: LIG   # 3-letter residue name of the ligand
  boundaries: 2.0
  basis: "6-31G*"
  fmo_level: 2
  nbody: 2
  mp2_level: true
  resdim: 2.0
  rcorsd: 2.0
  mwords: 125
  ngroup: 1
