system_type: protein_peptide

inputs:
  complex: complex_fcrn_fn001.pdb

output_dir: outputs

prep:
  cut_radius: 5.0
  # Mark genuine termini to avoid adding caps there:
  # true_nterm: ["A:1"]
  # true_cterm: ["A:300"]

fragit:
  central_fragment_resname: B     # only used for 2layer mode
  boundaries: 5.0
  basis: "6-31G(d)"
  calc_mode: "mp2"   # hf | mp2 | 2layer
  implicit_solvent: false
  nbody: 2
  resdim: 2.0
  rcorsd: 2.0
  mwords: 125
  ngroup: 1
